[workspace]
members = [
    "hashmap",
    "offcputime",
    "java-usdt",
    "drop",
    "bio",
    "protocol"
]

resolver = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true