// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::transmute_ptr_to_ref)]
#[allow(clippy::upper_case_acronyms)]
mod imp {
    use libbpf_rs::libbpf_sys;

    fn build_skel_config() -> libbpf_rs::Result<libbpf_rs::skeleton::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::skeleton::ObjectSkeletonConfigBuilder::new(DATA);
        builder.name("drop_bpf").prog("ping_drop");

        builder.build()
    }

    #[derive(Default)]
    pub struct DropSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'a> DropSkelBuilder {
        pub fn open(mut self) -> libbpf_rs::Result<OpenDropSkel<'a>> {
            let mut skel_config = build_skel_config()?;
            let open_opts = self.obj_builder.opts(std::ptr::null());

            let ret = unsafe { libbpf_sys::bpf_object__open_skeleton(skel_config.get(), &open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::System(-ret));
            }

            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(skel_config.object_ptr())? };

            Ok(OpenDropSkel { obj, skel_config })
        }

        pub fn open_opts(self, open_opts: libbpf_sys::bpf_object_open_opts) -> libbpf_rs::Result<OpenDropSkel<'a>> {
            let mut skel_config = build_skel_config()?;

            let ret = unsafe { libbpf_sys::bpf_object__open_skeleton(skel_config.get(), &open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::System(-ret));
            }

            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(skel_config.object_ptr())? };

            Ok(OpenDropSkel { obj, skel_config })
        }
    }

    pub struct OpenDropProgs<'a> {
        inner: &'a libbpf_rs::OpenObject,
    }

    impl<'a> OpenDropProgs<'a> {
        pub fn ping_drop(&self) -> &libbpf_rs::OpenProgram {
            self.inner.prog("ping_drop").unwrap()
        }
    }

    pub struct OpenDropProgsMut<'a> {
        inner: &'a mut libbpf_rs::OpenObject,
    }

    impl<'a> OpenDropProgsMut<'a> {
        pub fn ping_drop(&mut self) -> &mut libbpf_rs::OpenProgram {
            self.inner.prog_mut("ping_drop").unwrap()
        }
    }

    pub struct OpenDropSkel<'a> {
        pub obj: libbpf_rs::OpenObject,
        skel_config: libbpf_rs::skeleton::ObjectSkeletonConfig<'a>,
    }

    impl<'a> OpenDropSkel<'a> {
        pub fn load(mut self) -> libbpf_rs::Result<DropSkel<'a>> {
            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(self.skel_config.get()) };
            if ret != 0 {
                return Err(libbpf_rs::Error::System(-ret));
            }

            let obj = unsafe { libbpf_rs::Object::from_ptr(self.obj.take_ptr())? };

            Ok(DropSkel {
                obj,
                skel_config: self.skel_config,
                links: DropLinks::default(),
            })
        }

        pub fn progs(&self) -> OpenDropProgs {
            OpenDropProgs { inner: &self.obj }
        }

        pub fn progs_mut(&mut self) -> OpenDropProgsMut {
            OpenDropProgsMut { inner: &mut self.obj }
        }
    }

    pub struct DropProgs<'a> {
        inner: &'a libbpf_rs::Object,
    }

    impl<'a> DropProgs<'a> {
        pub fn ping_drop(&self) -> &libbpf_rs::Program {
            self.inner.prog("ping_drop").unwrap()
        }
    }

    pub struct DropProgsMut<'a> {
        inner: &'a mut libbpf_rs::Object,
    }

    impl<'a> DropProgsMut<'a> {
        pub fn ping_drop(&mut self) -> &mut libbpf_rs::Program {
            self.inner.prog_mut("ping_drop").unwrap()
        }
    }

    #[derive(Default)]
    pub struct DropLinks {
        pub ping_drop: Option<libbpf_rs::Link>,
    }

    pub struct DropSkel<'a> {
        pub obj: libbpf_rs::Object,
        skel_config: libbpf_rs::skeleton::ObjectSkeletonConfig<'a>,
        pub links: DropLinks,
    }

    unsafe impl<'a> Send for DropSkel<'a> {}
    unsafe impl<'a> Sync for DropSkel<'a> {}

    impl<'a> DropSkel<'a> {
        pub fn progs(&self) -> DropProgs {
            DropProgs { inner: &self.obj }
        }

        pub fn progs_mut(&mut self) -> DropProgsMut {
            DropProgsMut { inner: &mut self.obj }
        }

        pub fn attach(&mut self) -> libbpf_rs::Result<()> {
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(self.skel_config.get()) };
            if ret != 0 {
                return Err(libbpf_rs::Error::System(-ret));
            }

            self.links = DropLinks {
                ping_drop: (|| {
                    Ok(core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                        .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }))
                })()?,
            };

            Ok(())
        }
    }

    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 64, 0, 7, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46,
        115, 121, 109, 116, 97, 98, 0, 112, 114, 111, 103, 0, 108, 105, 99, 101, 110, 115, 101, 0, 100, 114, 111, 112, 46, 98,
        112, 102, 46, 99, 0, 112, 105, 110, 103, 95, 100, 114, 111, 112, 0, 95, 95, 108, 105, 99, 101, 110, 115, 101, 0, 46, 66,
        84, 70, 0, 46, 66, 84, 70, 46, 101, 120, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 30, 0, 0, 0, 4, 0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 41, 0, 0, 0, 18, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 51,
        0, 0, 0, 17, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 183, 0, 0, 0, 2, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0,
        0, 68, 117, 97, 108, 32, 77, 73, 84, 47, 71, 80, 76, 0, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 108, 1, 0, 0,
        108, 1, 0, 0, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 8, 0, 0, 4, 56, 0, 0, 0, 10, 0, 0, 0, 3, 0, 0,
        0, 0, 0, 0, 0, 15, 0, 0, 0, 3, 0, 0, 0, 64, 0, 0, 0, 24, 0, 0, 0, 3, 0, 0, 0, 128, 0, 0, 0, 34, 0, 0, 0, 3, 0, 0, 0, 192,
        0, 0, 0, 50, 0, 0, 0, 4, 0, 0, 0, 0, 1, 0, 0, 54, 0, 0, 0, 5, 0, 0, 0, 64, 1, 0, 0, 58, 0, 0, 0, 6, 0, 0, 0, 128, 1, 0,
        0, 67, 0, 0, 0, 6, 0, 0, 0, 160, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 16, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 2, 17, 0, 0, 0, 73, 0, 0, 0, 0, 0, 0, 8, 7, 0, 0, 0, 77, 0, 0, 0, 0, 0, 0, 8, 8, 0, 0, 0, 83, 0, 0, 0, 0,
        0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 13, 10, 0, 0, 0, 96, 0, 0, 0, 1, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0,
        1, 4, 0, 0, 0, 32, 0, 0, 1, 104, 0, 0, 0, 1, 0, 0, 12, 9, 0, 0, 0, 114, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 12, 0, 0, 0, 14, 0, 0, 0, 13, 0, 0, 0, 119, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0,
        0, 139, 0, 0, 0, 0, 0, 0, 14, 13, 0, 0, 0, 1, 0, 0, 0, 149, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 162, 0, 0, 0, 0, 0, 0, 7, 0,
        0, 0, 0, 247, 0, 0, 0, 1, 0, 0, 15, 13, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 13, 0, 0, 0, 0, 120, 100, 112, 95, 98, 117,
        102, 102, 0, 100, 97, 116, 97, 0, 100, 97, 116, 97, 95, 101, 110, 100, 0, 100, 97, 116, 97, 95, 109, 101, 116, 97, 0,
        100, 97, 116, 97, 95, 104, 97, 114, 100, 95, 115, 116, 97, 114, 116, 0, 114, 120, 113, 0, 116, 120, 113, 0, 102, 114, 97,
        109, 101, 95, 115, 122, 0, 102, 108, 97, 103, 115, 0, 117, 51, 50, 0, 95, 95, 117, 51, 50, 0, 117, 110, 115, 105, 103,
        110, 101, 100, 32, 105, 110, 116, 0, 99, 116, 120, 0, 105, 110, 116, 0, 112, 105, 110, 103, 95, 100, 114, 111, 112, 0,
        99, 104, 97, 114, 0, 95, 95, 65, 82, 82, 65, 89, 95, 83, 73, 90, 69, 95, 84, 89, 80, 69, 95, 95, 0, 95, 95, 108, 105, 99,
        101, 110, 115, 101, 0, 120, 100, 112, 95, 114, 120, 113, 95, 105, 110, 102, 111, 0, 120, 100, 112, 95, 116, 120, 113, 95,
        105, 110, 102, 111, 0, 47, 104, 111, 109, 101, 47, 109, 101, 47, 67, 76, 105, 111, 110, 80, 114, 111, 106, 101, 99, 116,
        115, 47, 101, 98, 112, 102, 95, 114, 115, 47, 100, 114, 111, 112, 47, 115, 114, 99, 47, 100, 114, 111, 112, 46, 98, 112,
        102, 46, 99, 0, 32, 32, 32, 32, 114, 101, 116, 117, 114, 110, 32, 88, 68, 80, 95, 80, 65, 83, 83, 59, 0, 108, 105, 99,
        101, 110, 115, 101, 0, 112, 114, 111, 103, 0, 159, 235, 1, 0, 32, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 20, 0, 0, 0, 28, 0,
        0, 0, 48, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 255, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 11, 0, 0, 0, 16, 0, 0, 0, 255, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 175, 0, 0, 0, 226, 0, 0, 0, 5, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 75, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 144, 0, 0, 0, 0, 0, 0, 0, 120, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 8,
        0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8,
        1, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 22,
        0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 1, 0, 0, 0, 0, 0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 61, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 40, 1, 0, 0, 0, 0, 0, 0, 136, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 66, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 176, 3, 0, 0, 0, 0, 0,
        0, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
