[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
anyhow = "1.0"
cpp_demangle = "0.4.2"
object = "0.31"
proc-maps = "0.3.1"
strum_macros="0.25"
plain = "0.2"
